### ISSUE TITLE
Each browser has own id?

### ISSUE THREAD

**Issue by KyleAMathews** [dominictarr/level-replicate#19]
So I successfully have got a master server talking to multiple browsers and changes are replicating quickly all around. Which is awesome! Prototyping a web app that'll work completely offline and sync changes on reconnect.

But to check my understanding, should each client have its own id? E.g. not MASTER-2 but something like BROWSER-1, BROWSER-2, etc?

**Comment by dominictarr** [comment]
Yes. You should use a UUID or something though. maybe this: https://www.npmjs.org/package/udid

**Comment by KyleAMathews** [comment]
Cool, thanks.
