### ISSUE TITLE
3 party replication

### ISSUE THREAD

**Issue by juliangruber** [dominictarr/level-replicate#8]
currently

a <-> b <-> c

replication doesn't work, if a is updated b is updated too, but c is not.

**Comment by juliangruber** [comment]
c is updated when the connection is recreated

**Comment by dominictarr** [comment]
use: `replicateDb.createStream({tail: true})`,
I think that should work.

**Comment by juliangruber** [comment]
it didn't the last time I tried, I'll make a pull request with a test.

**Comment by juliangruber** [comment]
hmm, the net-replicate3.js test passes...

**Comment by dominictarr** [comment]
Can you post your code, and/or make a pull request for the breaking case?

**Comment by hellboy81** [comment]
@dominictarr what parameter `{tail: true}` means?

**Comment by dominictarr** [comment]
@hellboy81 it means that after the databases are in sync, they will stay connected and replicate any updates as they happen.
